const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const logger = require('./logger');

/**
 * Generate PDF from CV data
 * @param {Object} cv - CV object with data
 * @param {String} outputPath - Where to save the PDF
 * @returns {Promise<String>} Path to generated PDF
 */
const generateCVPDF = (cv, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      // Create PDF document
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      // Create file
      const stream = fs.createWriteStream(outputPath);
      
      stream.on('error', (error) => {
        logger.error('PDF stream error:', error);
        reject(error);
      });

      doc.pipe(stream);

      // Header - Name and Contact Info
      doc.fontSize(24).font('Helvetica-Bold').text(cv.firstName + ' ' + cv.lastName, {
        align: 'center',
      });

      doc.fontSize(10).font('Helvetica').text(cv.email || '', {
        align: 'center',
      });

      if (cv.phoneNumber) {
        doc.text(cv.phoneNumber, { align: 'center' });
      }

      doc.moveDown(0.5);
      doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);

      // Professional Summary
      if (cv.bio) {
        doc.fontSize(12).font('Helvetica-Bold').text('PROFESSIONAL SUMMARY', {
          underline: true,
        });
        doc.fontSize(10).font('Helvetica').text(cv.bio);
        doc.moveDown(0.5);
      }

      // Experience
      if (cv.experience && cv.experience.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('EXPERIENCE', {
          underline: true,
        });

        cv.experience.forEach((exp) => {
          doc.fontSize(11).font('Helvetica-Bold').text(exp.jobTitle || '');
          doc.fontSize(10).font('Helvetica').text(exp.company || '', {
            color: '#666666',
          });
          
          if (exp.startDate || exp.endDate) {
            const dates = `${exp.startDate || ''} - ${exp.endDate || 'Present'}`;
            doc.text(dates, { color: '#999999' });
          }

          if (exp.description) {
            doc.fontSize(9).text(exp.description);
          }

          doc.moveDown(0.3);
        });

        doc.moveDown(0.5);
      }

      // Education
      if (cv.education && cv.education.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('EDUCATION', {
          underline: true,
        });

        cv.education.forEach((edu) => {
          doc.fontSize(11).font('Helvetica-Bold').text(edu.degree || '');
          doc.fontSize(10).font('Helvetica').text(edu.school || '', {
            color: '#666666',
          });

          if (edu.graduationDate) {
            doc.fontSize(9).text(`Graduated: ${edu.graduationDate}`, {
              color: '#999999',
            });
          }

          if (edu.description) {
            doc.fontSize(9).text(edu.description);
          }

          doc.moveDown(0.3);
        });

        doc.moveDown(0.5);
      }

      // Skills
      if (cv.skills && cv.skills.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('SKILLS', {
          underline: true,
        });

        const skillsText = cv.skills.map(s => s.name || s).join(', ');
        doc.fontSize(10).font('Helvetica').text(skillsText);
        doc.moveDown(0.5);
      }

      // Languages
      if (cv.languages && cv.languages.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('LANGUAGES', {
          underline: true,
        });

        cv.languages.forEach((lang) => {
          const level = lang.proficiency ? ` - ${lang.proficiency}` : '';
          doc.fontSize(10).font('Helvetica').text(`${lang.name}${level}`);
        });

        doc.moveDown(0.5);
      }

      // Certifications
      if (cv.certifications && cv.certifications.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('CERTIFICATIONS', {
          underline: true,
        });

        cv.certifications.forEach((cert) => {
          doc.fontSize(10).font('Helvetica').text(`${cert.name}`);
          if (cert.issuer) {
            doc.fontSize(9).text(`Issued by: ${cert.issuer}`, {
              color: '#999999',
            });
          }
          doc.moveDown(0.2);
        });
      }

      // Footer
      doc.fontSize(8).text('Generated by CV Maker', {
        align: 'center',
        color: '#cccccc',
      });

      // Finalize PDF
      doc.end();

      // Wait for file to be written
      stream.on('finish', () => {
        logger.info('PDF generated successfully:', outputPath);
        resolve(outputPath);
      });
    } catch (error) {
      logger.error('PDF generation error:', error);
      reject(error);
    }
  });
};

/**
 * Generate simple PDF with HTML-like formatting
 * @param {String} title - PDF title
 * @param {String} content - PDF content text
 * @param {String} outputPath - Where to save the PDF
 * @returns {Promise<String>} Path to generated PDF
 */
const generateSimplePDF = (title, content, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const stream = fs.createWriteStream(outputPath);

      stream.on('error', (error) => {
        logger.error('PDF stream error:', error);
        reject(error);
      });

      doc.pipe(stream);

      // Title
      if (title) {
        doc.fontSize(20).font('Helvetica-Bold').text(title);
        doc.moveDown();
      }

      // Content
      doc.fontSize(12).font('Helvetica').text(content);

      // Footer with date
      doc.fontSize(8).text(`Generated on ${new Date().toLocaleString()}`, {
        align: 'center',
        color: '#cccccc',
      });

      doc.end();

      stream.on('finish', () => {
        logger.info('Simple PDF generated successfully:', outputPath);
        resolve(outputPath);
      });
    } catch (error) {
      logger.error('Simple PDF generation error:', error);
      reject(error);
    }
  });
};

module.exports = {
  generateCVPDF,
  generateSimplePDF,
};
